config/routes.rb
Rails.application.routes.draw do
  root to: 'animals#index'
  resources :animals do
    resources :sightings
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :sightings, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ApplicationRecord
  belongs_to :animal
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    if params[:search]
      @animals = Animal.where(name: params[:search])
      render :index
    else
      @animals = Animal.all
      render :index
    end
  end

  def new
    @animal = Animal.new
    :new
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to animals_path
    else
      render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
    render :edit
  end

  def show
    @animal = Animal.find(params[:id])
    render :show
  end

  def update
    @animal= Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to animals_path
    else
      render :edit
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_path
  end

  private
  def animal_params
    params.require(:animal).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  def new
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new
    render :new
  end

def create
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new(sighting_params)
    if @sighting.save
      redirect_to animal_path(@animal)
    else
      render :new
    end
end

 def show
   @animal = Animal.find(params[:animal_id])
   @sighting = Sighting.find(params[:id])
   render :show
 end

 def edit
   @animal = Animal.find(params[:animal_id])
   @sighting = Sighting.find(params[:id])
   render :edit
 end

 def update
   @sighting = Sighting.find(params[:id])
   if @sighting.update(sighting_params)
     redirect_to animal_path(@sighting.animal)
   else
     render :edit
   end
 end

 def destroy
  @sighting = Sighting.find(params[:id])
  @sighting.destroy
  redirect_to animal_path(@sighting.animal)
end


 private
    def sighting_params
      params.require(:sighting).permit(:location, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/edit.html.erb
<h1>Edit animal</h1>

<%= form_for @animal do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/animals/index.html.erb
<h1>Animal</h1>
<h4>Search for animal</h4>

<%= form_tag animals_path, :method => 'get'  do %>
  <%= text_field_tag :search, params[:search]%>
  <%= submit_tag "Search", :name => nil  %>
<% end %>

<% if @animals.any? %>
  <ul>
    <% @animals.each do |animal| %>
      <li><%= link_to animal.name, animal_path(animal) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no animals yet.</p>
<% end %>


<p><%= link_to "Create new animal", new_animal_path %></p>

app/views/animals/new.html.erb
<h1>New animal</h1>

<%= form_for @animal do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/animals/show.html.erb
<h1><%= @animal.name %></h1>

<% if @animal.sightings.any? %>
  <h4>Here are the sighting for this animal:</h4>

  <%= form_tag animal_path, :method => 'get'  do %>
    <%= date_field_tag :search, params[:search]%>
    <%= submit_tag "Search", :name => nil  %>
  <% end %>


  <% if params[:search] %>
  <%sightings = @animal.sightings.where(:time == params[:search]) %>
<ul>

<% sightings.each do |sighting| %>
<li>  <%= link_to sighting.location, animal_sighting_path(@animal, sighting) %></li>
<%end%>
</ul>
  <% else %>
  <% @animal.sightings.each do |sighting| %>
    <ul>
      <li>
        <%= link_to sighting.location, animal_sighting_path(@animal, sighting) %>
      </li>
    </ul>
  <% end %>
  <% end %>
<% else %>
  <p>No sighting are listed for this animal.</p>
<% end %>

<p><%= link_to "Add a sighting", new_animal_sighting_path(@animal) %></p>

<p><%= link_to "Edit", edit_animal_path(@animal) %></p>
<p><%= link_to "Delete animal", animal_path(@animal),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to animals", animals_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag  'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

    <%= yield %>
  </div>
  </body>
</html>

app/views/sightings/edit.html.erb
<h1>Edit sighting:</h1>

<%= form_for [@animal, @sighting] do |f| %>
<%= f.label :location%>
<%= f.select :location, ['Mountain', 'Plain', 'Desert', 'Hill', 'Forrest', 'Jungle']%>
<%= f.label :time%>
<%= f.date_field :time %>
<p><%= f.submit %></p>
<% end %>

app/views/sightings/new.html.erb
<h1>Add a new sighting:</h1>

<%= form_for [@animal, @sighting] do |f| %>
<%= f.label :location%>
<%= f.select :location, ['Mountain', 'Plain', 'Desert', 'Hill', 'Forrest', 'Jungle']%>
<%= f.label :time%>
<%= f.date_field :time %>
<p><%= f.submit %></p>
<% end %>

app/views/sightings/show.html.erb
<h1>Location: <%= @sighting.location %></h1>
<h2>Animal: <%= @animal.name %></h2>
<h3>Seen at: <%= @sighting.time %></h3>

<p><%= link_to "Edit sighting", edit_animal_sighting_path(@animal, @sighting) %></p>
<p><%= link_to "Delete sighting", animal_sighting_path(@animal, @sighting),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to animal", animal_path(@animal) %></p>